# Generated by Django 5.2.11 on 2026-03-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueup', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='game_name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
