# Generated by Django 6.0.3 on 2026-03-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueup', '0007_remove_post_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
