# Generated by Django 5.2.11 on 2026-03-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueup', '0008_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
